stages:
  preprocessing:
    cmd: python data_preprocessing.py
    deps:
      - data_clearing.py
      - config.py
      - data/master.csv
    params:
      - Datapick.null_threshold
      - Datapick.country_name
      - Datapick.year
      - Datapick.random_state
      - Datapick.test_size
    outs:
      - data/train_test.npy
      - data/dataframe_plot.csv
  linreg:
    cmd: python Linear_reg.py
    deps:
      - data/train_test.npy
      - data_preprocessing.py
      - config.py
    outs:
      - data/linreg.npy
  olsreg:
    cmd: python OLS_reg.py
    deps:
      - data/train_test.npy
      - data_preprocessing.py
      - config.py
    outs:
      - data/olsreg.npy
  polyreg:
    cmd: python Polynomial_reg.py
    deps:
      - data/train_test.npy
      - data_preprocessing.py
      - config.py
    params:
      - polyreg.degrees
    outs:
      - data/polyreg.npy
  compare:
    cmd: python Comparison.py
    deps:
      - data/linreg.npy
      - data/olsreg.npy
      - data/polyreg.npy
      - config.py
    outs:
      - data/results.csv
  plotting:
    cmd: python plotting_data.py
    deps:
      - data_clearing.py
      - data_visualization.py
      - data/dataframe_plot.csv
      - config.py
    outs:
      - plots/desc_plot.png
      - plots/heat_map.png
      - plots/scatter_plot.png
      - plots/histogram.png
      - plots/time_series_plot.png
plots:
  - plots/desc_plot.png
  - plots/heat_map.png
  - plots/scatter_plot.png
  - plots/histogram.png
  - plots/time_series_plot.png