Datapick:
  null_threshold: 1000
  country_name: ''
  year: 0
  random_state: 42
  test_size: 0.2
polyreg:
  degrees: [2,3,4]
plotting:
  scatter_plot_var1: 'population'
  scatter_plot_var2: 'suicide_number'
  histogram_var: 'population'
  histogram_bins: 15








